server:
  port: ${PORT:8888}

security:
  user:
    password: password

management:
  context-path: /admin

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
    metadataMap:
      password: ${security.user.password}
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka.credentials.uri:http://user:password@localhost:8761/eureka/}

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/david-noel/spring-cloud-sample-config


endpoints:
  health:
    sensitive: false